### ISSUE TITLE
Kindly update docker image

### ISSUE THREAD

**Issue by rishiraj** [tensorlakeai/indexify#344]
The current docker image (pushed 7 days ago) still uses http://localhost:8900/repositories/default instead of http://localhost:8900/namespaces/default which results to exception:
```
exception: Client error '404 Not Found' for url 'http://localhost:8900/namespaces/default'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404, response text: 
Traceback (most recent call last):
  File "/Users/rishiraj/tensorlake/project2/test.py", line 3, in <module>
    client = IndexifyClient()
             ^^^^^^^^^^^^^^^^
  File "/Users/rishiraj/miniconda3/lib/python3.11/site-packages/indexify/client.py", line 50, in __init__
    response = self.get(f"namespaces/{self.namespace}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishiraj/miniconda3/lib/python3.11/site-packages/indexify/client.py", line 128, in get
    return self._request("GET", url=f"{self._service_url}/{endpoint}", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishiraj/miniconda3/lib/python3.11/site-packages/indexify/client.py", line 110, in _request
    raise exc
  File "/Users/rishiraj/miniconda3/lib/python3.11/site-packages/indexify/client.py", line 107, in _request
    response.raise_for_status()
  File "/Users/rishiraj/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://localhost:8900/namespaces/default'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
```
i am using the latest code for [python client](https://github.com/tensorlakeai/indexify-python-client) and installed from source.
http://localhost:8900/repositories/default returns: {"repository":{"name":"default","extractor_bindings":[]}}
http://localhost:8900/namespaces/default returns HTTP ERROR 404

**Comment by diptanu** [comment]
This is done.
