### ISSUE TITLE
Error Traces While Working on Examples

### ISSUE THREAD

**Issue by stangirala** [tensorlakeai/indexify#909]
Some exceptions while setting up the readme

```
Traceback (most recent call last):
  File "/Users/<user>/git/indexify/examples/readme/readme_example.py", line 57, in <module>
    result = g.graph_outputs(invocation_id, "tripled")
  File "/Users/<user>/git/indexify/python-sdk/indexify/functions_sdk/sup_graph.py", line 56, in graph_outputs
    return self.client.graph_outputs(
  File "/Users/<user>/git/indexify/python-sdk/indexify/local_client.py", line 170, in graph_outputs
    raise ValueError(f"no results found for fn {fn_name} on graph {graph}")
ValueError: no results found for fn tripled on graph sequence_summer

----
Traceback (most recent call last):
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/opt/homebrew/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user>/git/indexify/python-sdk/indexify/remote_client.py", line 77, in _request
    response = self._client.request(method, timeout=self._timeout, **kwargs)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/homebrew/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/<user>/git/indexify/ENV/lib/python3.9/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/git/indexify/examples/readme/readme_example.py", line 89, in <module>
    run_remote(3, "squared")
  File "/Users/<user>/git/indexify/examples/readme/readme_example.py", line 53, in run_remote
    g = SupGraph(
  File "/Users/<user>/git/indexify/python-sdk/indexify/functions_sdk/sup_graph.py", line 26, in __init__
    self.client.register_compute_graph(self.graph)
  File "/Users/<user>/git/indexify/python-sdk/indexify/remote_client.py", line 165, in register_compute_graph
    response = self._post(
  File "/Users/<user>/git/indexify/python-sdk/indexify/remote_client.py", line 145, in _post
    return self._request("POST", url=f"{self._service_url}/{endpoint}", **kwargs)
  File "/Users/<user>/git/indexify/python-sdk/indexify/remote_client.py", line 89, in _request
    ex = ApiException(status="ConnectionError", message=message)
TypeError: __init__() got an unexpected keyword argument 'status'
```

**Comment by PulkitMishra** [comment]
related #892
